backend:
  name: git-gateway

publish_mode: "editorial_workflow"

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Alt", name: "alt", widget: "string", required: false}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Services Button", name: "services_button", widget: "string" }
          - { label: "Values Button", name: "values_button", widget: "string" }
          - {
              label: "Blurb",
              name: "blurb",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Intro",
              name: "intro",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Services Intro",
              name: "services_intro",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Alt", name: "alt", widget: "string"},
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Values",
              name: "values",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Alt", name: "alt", widget: "string"},
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                  { label: "Subtext", name: "subtext", widget: "text" }                  
                ],
            }
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" } 
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Contact Entries"
            name: "contact_entries"
            widget: "list"
            fields: [
              { label: "Heading", name: "heading", widget: "string" },
              { label: "Text", name: "text", widget: "text" }
              ]
      - file: "site/content/services/_index.md"
        label: "Services Page"
        name: "services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Intro",
                name: "intro",
                widget: "object",
                fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Description", name: "description", widget: "text" },
                ],
            }
          - {
              label: "Services List",
              name: services_list,
              widget: list,
              fields:
                [
                  { label: "Single Image", name: single_image, widget: object, fields: 
                    [
                      {label: "Layout", name: layout, widget: select, options: ["large-image", "image-left", "image-right"]},
                      {label: "Heading", name: heading, widget: string},
                      {label: "Image", name: image, widget: image},
                      {label: "Alt", name: alt, widget: string},
                      {label: "Description", name: description, widget: list, field: 
                        {label: "Text", name: text, widget: text}
                      }
                    ]
                  },
                  { label: "Two Image", name: two_image, widget: object, fields:
                    [
                      {label: "Layout", name: layout, widget: hidden, default: "two-image"},
                      {label: "Heading", name: heading, widget: string},
                      {label: "Description", name: description, widget: list, field: 
                        {label: "Text", name: text, widget: text}
                      },
                      {label: "Image1", name: image1, widget: object, fields: 
                        [
                        {label: "Image", name: image, widget: image},
                        {label: "Alt", name: alt, widget: string},
                        {label: "Text", name: text, widget: text}
                        ]
                      },
                      {label: "Image2", name: image2, widget: object, fields:
                        [
                        {label: "Image", name: image, widget: image},
                        {label: "Alt", name: alt, widget: string},
                        {label: "Text", name: text, widget: text}
                        ]}
                    ]
                  }
                ],
            }  
          - {
              label: "Testimonials",
              name: "testimonials",
              widget: "list",
              fields:
                [
                  { label: "Quote", name: "quote", widget: "string" },
                  { label: "Author", name: "author", widget: "string" },
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Company", name: "company", widget: "string"},
                  { label: "Website", name: "Website", widget: "string"},
                ],
            }

      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string"}
          - label: "Values"
            name: "values"
            widget: "list"
            fields: [
              { label: "Heading", name: "heading", widget: "string" },
              { label: "Text", name: "text", widget: "text" },
              { label: "Subtext", name: "subtext", widget: "text" },
              { label: "Image", name: "imageUrl", widget: "image" },
              { label: "Alt", name: "alt", widget: "string"}
              ]
          - { label: "Bio Heading", name: "bio_heading", widget: "string", default: "Meet the Founder"}
          - label: "Bios"
            name: "bios"
            widget: "list"
            fields: [
              {label: "Image", name: "image", widget: "image"},
              { label: "Name", name: "name", widget: "string" },
              { label: "Position", name: "position", widget: "string"},
              {label: "Description", name: "description", widget: "list", field:
                 {label: "Text", name: "text", widget: "string"},
              }
              ]